id: P008131
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:38.131798
source_metadata:
  id: bdr:W1AC288
  title: 'རྒུད། '
  author: ''
  volumes:
    51a07a9eaad641aeae3e85cc9e23ed32:
      image_group_id: I2PD17794
      title: Volume 1 of rgud/
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
