id: P008131
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC288
  title: 'རྒུད། '
  author: ''
  volumes:
    ddc2fc5722fe4001bf57cfd50adffa65:
      image_group_id: I2PD17794
      title: ''
      volume_number: 1
      total_pages: 346
ebook_metadata:
  title: 'རྒུད། '
  author: ''
  sku: P008131
  cover: cover.jpg
  layers:
  - pagination
