id: opecha:P008131
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC288
  title: 'རྒུད། '
  volume:
    51a07a9eaad641aeae3e85cc9e23ed32:
      image_group_id: I2PD17794
      title: Volume 1 of rgud/
      volume_number: 1
      total_pages: 346
  author: ''
ebook_metadata:
  title: 'རྒུད། '
  author: ''
  sku: P008131
  cover: cover.jpg
  layers:
  - pagination
